### ISSUE TITLE
发现个错误

### ISSUE THREAD

**Issue by cjcj125125** [xiaokun19931126/LoadingView#1]
java.lang.ArrayIndexOutOfBoundsException: length=1; index=3
   at com.xiaokun.dialogtiplib.dialog_tip.FadeInTextView$1.onAnimationUpdate(FadeInTextView.java:111)
                      at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1522)

![qq 20180530112829](https://user-images.githubusercontent.com/20206579/40697398-9a3d7798-63fc-11e8-8c0a-c2cd987826a8.png)

**Comment by cjcj125125** [comment]
FadeInTextView类的109行条件改一下  ：currentIndex != index&&index<arr.length

**Comment by Xiaocai9527** [comment]
我这边运行了下没问题，从代码上看也是没什么问题。因为初始化时这句代码
arr = new String[textCount];
是不是你自己改了代码，当然你这个加上去防错更好。

**Comment by cjcj125125** [comment]
arr = new String[textCount]; 这么加的话肯定不对吧，textCount初始值为0，那么你数组长度就是0了，代码我是直接clone下来运行的，没有改动就报错了你可以把你的代码和线上的对比一下

**Comment by Xiaocai9527** [comment]
我是刚clone下来运行的。你自己好好看看setTextString这个方法；
